### ISSUE TITLE
The "repeat password" field in the registration form shows the password

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index-gui#142]
![image](https://github.com/torrust/torrust-index-frontend/assets/58816/b19dd498-6ad9-4772-b7be-f395e740cf5e)

I think we should also use the type "password" for the field.

**Comment by da2ce7** [comment]
We should use the full HTML5 standard: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/password for both. I think that having a reveal and html5 validation would be nice also.

**Comment by josecelano** [comment]
> We should use the full HTML5 standard: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/password for both. I think that having a reveal and html5 validation would be nice also.

OK, I suppose we can overhaul the registration and login forms:

This relates to: https://github.com/torrust/torrust-index-backend/issues/92

### TODO

- [x] Validate email in the frontend and backend.
- [x] Fix a bug. When you select a text dragging the form is closed if the dragging ends outside the form.
- [x] Toggle to reveal password.
- [x] Hidden password for "password" and "repeat password" fields, with reveal option.
- [x] Consider creating two different Vue components for the registration and login form. There is only one. From my point of view, two forms would increase the readability (single responsibility)

### Other considerations

- Follow HTML5 standards
- Consider redirection to the login form after submitting the registration form or directly authenticate the user if email verification is not required.
