### ISSUE TITLE
Add E2E tests

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index-gui#148]
After [setting up the scaffolding for E2E testing](https://github.com/torrust/torrust-index-frontend/issues/144), we can now add some E2E tests for the essential features.

I think we could implement the same tests we have in the backend (or at least a subset):

https://github.com/torrust/torrust-index-backend/tree/develop/tests/e2e/web/api/v1/contexts

**IMPORTANT**: if you'd like to contribute, you can pick up a test and open a new issue. This issue only keeps track of all the E2E tests pending implementation.

### Guest

- [x] Registration
- List torrents
  - [ ] With no torrents
  - [ ] With pagination
  - [ ] With `table` mode
  - [ ] Filtering by category
  - [ ] Filtering by tag
  - [ ] Searching for words in the torrent title
  - [ ] Sorting by newest/oldest
  - [ ] Sorting by seeders/leechers
  - [x] https://github.com/torrust/torrust-index-frontend/issues/232
  - [ ] See metadata: title, description, category, tags
  - [ ] See the number of leechers/seeders
  - [x] https://github.com/torrust/torrust-index-frontend/issues/221
  - [x] https://github.com/torrust/torrust-index-frontend/issues/230

### Registered user

- [x] https://github.com/torrust/torrust-index-frontend/issues/178
- [x] https://github.com/torrust/torrust-index-frontend/issues/180
- [ ] Edit torrent info/metadata (title, description, category, tags)
- [ ] Advanced torrent edition:
  - [ ] Use markdown in the torrent description (for example, a bold text).
  - [ ] Use proxied images (JPG or PNG).

### Admin

Categories

- [x] https://github.com/torrust/torrust-index-frontend/issues/224
- [x] https://github.com/torrust/torrust-index-frontend/issues/226

Tags

- [ ] https://github.com/torrust/torrust-index-frontend/issues/228
- [ ] https://github.com/torrust/torrust-index-frontend/issues/229

Backend settings

- [ ] View backend settings

We can create subtasks for one or multiple E2E tests depending on how hard it is to implement them.

### Subtasks

- https://github.com/torrust/torrust-index-frontend/issues/144
