### ISSUE TITLE
Ovehaul containerization

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index-gui#349]
We made a lot of changes in the [Tracker](https://github.com/torrust/torrust-tracker) and [Index](https://github.com/torrust/torrust-index). Those changes are explained in this blog post: [Containerizing Rust Applications](https://torrust.com/containerizing-rust-applications-best-practices).

We should also apply some of them to this repo and other updates/improvements. This issue is to track them.

### Subtasks

- [x] Rename `Dockerfile` to `Containerfile`.
- [x] https://github.com/torrust/torrust-index-gui/issues/344
- [x] https://github.com/torrust/torrust-index-gui/issues/363
- [x] https://github.com/torrust/torrust-index-gui/issues/295
- [x] https://github.com/torrust/torrust-index-gui/issues/263
- [x] https://github.com/torrust/torrust-index-gui/issues/375
- [x] https://github.com/torrust/torrust-index-gui/issues/182
- [x] https://github.com/torrust/torrust-index-gui/issues/183
- [x] https://github.com/torrust/torrust-index-gui/issues/381

**Comment by josecelano** [comment]
Done. We only have to [review the README and docs](https://github.com/torrust/torrust-index-gui/issues/379) to update info related to containers.
