### ISSUE TITLE
Update footer

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index-gui#401]
From:  Powered by Torrust ⚡ Copyright © 2023 (Frontend and Backend)
To: Powered by Torrust ⚡ Copyright © 2024 (Index GUI and Index)

**Comment by mario-nt** [comment]
@josecelano @da2ce7 

After some research, I noticed that a lot of websites have the license and copyright info on the website itfels, so maybe we can create a new page called license, and inside, have two components, one for the GUI and the other for the index, containing all the info regarding the license. 

It takes more time to maintain than just a link to the license file in the repo, we I think it looks better, and we only have to copy/paste any updates from the readme file, we can even use the markup component to keep the style.

A quick mockup looks like this:

![image](https://github.com/torrust/torrust-index-gui/assets/141633147/18a1e4e8-28dc-4f61-aae8-df07f43a3428)

**Comment by da2ce7** [comment]
To (Option 2): Powered by Torrust ⚡ Copyright © 2024 (Index and Interface)

**Comment by mario-nt** [comment]
### Tasks:

- [x] Update year and link
- [x] GUI license page
~~- [ ]  Index license page~~
- [x] Fetch file composable
- [x] License formatting
- [ ] Cleanup and final touches

**Comment by mario-nt** [comment]
Before implementing the final version, I wanted to clarify how the license is going to be displayed, so we don't waste time coding iterations we don't agree on.


### Footer


I would change the footer to a more simplified version:

![image](https://github.com/torrust/torrust-index-gui/assets/141633147/40584edf-b39b-4cb6-91d2-5521880cb302)

_Notice the link to the license/copyright page_


### Licenses

**Option 1:** 

Only the GUI license is shown in the GUI, if the user wants to know more about the index or tracker license, the will have to go to the /license endpoint of each app, the one for the index is already implemented:

![image](https://github.com/torrust/torrust-index-gui/assets/141633147/d481ac91-2992-4bf3-93e5-e1cfb67fca53)


We could do the same for the tracker.


**Option 2:** 

Displaying the GUI and index license in the GUI. 

We create a new page and display the data from the license file/s, so every time we make changes, they are automatically updated in the GUI.

**Option 3:** 

Displaying all three licenses in a new page in the Torrust website, we could create a link to this page from all three apps.

**Option 4:**

Having a license page in all 4 sites, this is the one I like the most.

In the Torrust website, we could have a license page with all three project's licenses, and also, have a license page in every project. We can have a template with raw HTML so the style is consistent. 

This approach also helps with keeping the projects more decoupled from each others.

What do you think @da2ce7 @josecelano @cgbosse

**Comment by josecelano** [comment]
Hi @mario-nt, in my opinion:

- We should include the license in each deployable artefact. I mean the running services should show their license at the time those artifacts were built because the license might have changed.
- We should include in each software piece only its license, to avoid updating all projects when the license for one project changes.
- The website is a little bit different. I think the website could have a page explaining the licenses in all projects. The latest version of the license that is being used at the moment.

In summary, I like option 4, but I would not include all projects' licenses in all projects. I would:

1. Include a `/license` page on the Torrust Website explaining the latest licenses for all projects.
2. Include an embedded license in all running projects. Only its license and a link to https://torrust.com/licenses to get more info for other projects' licenses.

The way we can embed the license in each project is:

- Index GUI. A new page for the Index GUI: https://index.torrust-demo.com/licenses
- Index. It's already done: https://index.torrust-demo.com/api/v1/about/license
- Tracker. We could also add a license endpoint to the Tracker API.

**Comment by mario-nt** [comment]
@josecelano What you suggested is exactly what I really meant, I didn't explain myself well enough.

**Comment by cgbosse** [comment]
Option  4 good for me too.
