### ISSUE TITLE
User self-management features

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index-gui#649]
An EPIC to track issues related to:

- User account: essential user info needed to identify users (username, email, ...)
- User settings: especially customizations like date format, default layouts, ...
- User profile: publicly exposed users' data

**NOTE:** all issues will primarily affect standard users, meaning they affect what the standard users can do with their data.

### User account

- [ ] https://github.com/torrust/torrust-index-gui/issues/469
- [ ] https://github.com/torrust/torrust-index-gui/issues/648

### User settings

- [ ] https://github.com/torrust/torrust-index-gui/issues/651
- [ ] https://github.com/torrust/torrust-index-gui/issues/652
- [ ] https://github.com/torrust/torrust-index-gui/issues/653

### User profile

- [ ] https://github.com/torrust/torrust-index-gui/issues/650
- [ ] https://github.com/torrust/torrust-index-gui/issues/655
- [ ] https://github.com/torrust/torrust-index-gui/issues/656
