### ISSUE TITLE
Index administration

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index-gui#657]
An EPIC to track issues related to index administration.

- Administration tasks
  - User management
    - Basic user management
      - [x] https://github.com/torrust/torrust-index-gui/issues/658
      - [x] https://github.com/torrust/torrust-index-gui/issues/659
      - [ ] https://github.com/torrust/torrust-index-gui/issues/698
      - [ ] https://github.com/torrust/torrust-index-gui/issues/660
      - [ ] https://github.com/torrust/torrust-index-gui/issues/661
      - Filter and sort users in admin panel
    - Users restrictions
      - [ ] https://github.com/torrust/torrust-index-gui/issues/663
      - [ ] https://github.com/torrust/torrust-index-gui/issues/662
    - Invitations
      - Create invitations
      - Option for users to only register with an invite link
  - [ ] https://github.com/torrust/torrust-index-gui/issues/283
- Dynamic global settings (runtime settings)
  - [ ] https://github.com/torrust/torrust-index-gui/issues/664
  - Registration
    - [ ] https://github.com/torrust/torrust-index-gui/issues/665
  - Torrenting
    - [ ] https://github.com/torrust/torrust-index-gui/issues/666
  - UI
    - UI customization
      - [ ] https://github.com/torrust/torrust-index-gui/issues/669
      - [ ] https://github.com/torrust/torrust-index-gui/issues/637
      - [ ] https://github.com/torrust/torrust-index-gui/issues/668
      - [ ] https://github.com/torrust/torrust-index-gui/issues/670
      - Customisable torrent URLS
  - Confidentiality
    - [ ] https://github.com/torrust/torrust-index-gui/issues/667

**NOTE:** All dynamic global settings depend on setting up the scaffolding for dynamic global settings
