### ISSUE TITLE
Admins should be able to list users

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index-gui#658]
Parent issue: https://github.com/torrust/torrust-index-gui/issues/657

Add a new tab to the "Admin Settings" panel to list users:

![image](https://github.com/user-attachments/assets/2dbc9764-f177-447b-9fa5-23cf658203ac)

This first version can only contain: `username`, `email`.

In the future, it can contain statistics and other actions.

**Comment by mario-nt** [comment]
###  Depends on

- [x] https://github.com/torrust/torrust-index/issues/796
- [x] https://github.com/torrust/torrust-index-api-lib/issues/49
- [x] https://github.com/torrust/torrust-index-types-lib/issues/28


### To-Do:

- [x] New placeholder admin panel tab
- [x] Logic to get the list of users from the index
- [x] Admin panel tab Styling
- [x] Add pagination to the list of results
